dist: bionic
sudo: required
script:
- echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
- curl https://bazel.build/bazel-release.pub.gpg | apt-key add -
- sudo apt-get update && sudo apt-get install bazel
- bazel test :test_version
addons:
  apt:
    packages:
    - curl
