dist: bionic
sudo: required
install:
- sudo echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
- sudo curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
- sudo apt-get update
- sudo apt-get install bazel
script:
- bazel run //pythonreq:install_requirements
- bazel test :test_version
- bazel run //pyinstallerw:run
- ./bazel-out/k8-fastbuild/bin/pyinstallerw/run.runfiles/__main__/dist/hello
addons:
  apt:
    packages:
    - curl
    - gcc
